# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import message_pb2 as message__pb2


class SFVMessageStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SFMessage = channel.unary_unary(
                '/SFVMessage/SFMessage',
                request_serializer=message__pb2.SingleFloatValueMessage.SerializeToString,
                response_deserializer=message__pb2.Response.FromString,
                )


class SFVMessageServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SFMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SFVMessageServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SFMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SFMessage,
                    request_deserializer=message__pb2.SingleFloatValueMessage.FromString,
                    response_serializer=message__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SFVMessage', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SFVMessage(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SFMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SFVMessage/SFMessage',
            message__pb2.SingleFloatValueMessage.SerializeToString,
            message__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
