# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='message.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rmessage.proto\";\n\x17SingleFloatValueMessage\x12\x11\n\tdevice_id\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x02\"\x1c\n\x08Response\x12\x10\n\x08response\x18\x01 \x01(\x08\x32@\n\nSFVMessage\x12\x32\n\tSFMessage\x12\x18.SingleFloatValueMessage\x1a\t.Response\"\x00\x62\x06proto3'
)




_SINGLEFLOATVALUEMESSAGE = _descriptor.Descriptor(
  name='SingleFloatValueMessage',
  full_name='SingleFloatValueMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='device_id', full_name='SingleFloatValueMessage.device_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='SingleFloatValueMessage.value', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=76,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='Response.response', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=106,
)

DESCRIPTOR.message_types_by_name['SingleFloatValueMessage'] = _SINGLEFLOATVALUEMESSAGE
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SingleFloatValueMessage = _reflection.GeneratedProtocolMessageType('SingleFloatValueMessage', (_message.Message,), {
  'DESCRIPTOR' : _SINGLEFLOATVALUEMESSAGE,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:SingleFloatValueMessage)
  })
_sym_db.RegisterMessage(SingleFloatValueMessage)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:Response)
  })
_sym_db.RegisterMessage(Response)



_SFVMESSAGE = _descriptor.ServiceDescriptor(
  name='SFVMessage',
  full_name='SFVMessage',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=108,
  serialized_end=172,
  methods=[
  _descriptor.MethodDescriptor(
    name='SFMessage',
    full_name='SFVMessage.SFMessage',
    index=0,
    containing_service=None,
    input_type=_SINGLEFLOATVALUEMESSAGE,
    output_type=_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SFVMESSAGE)

DESCRIPTOR.services_by_name['SFVMessage'] = _SFVMESSAGE

# @@protoc_insertion_point(module_scope)
